# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/0-Card.ipynb.

# %% auto 0
__all__ = ['CHAT_DIV_ID', 'ChatCard', 'render_chat_list', 'mk_inp']

# %% ../../nbs/0-Card.ipynb 2
from fasthtml.common import *
from .design_system import get_color, get_spacing, get_typography, get_border_radius, get_breakpoint, get_mobile_media_query

# %% ../../nbs/0-Card.ipynb 4
class ChatCard:
    def __init__(
        self,
        user_color: str = None,
        assistant_color: str = None,
        user_emoji: str = "🗣️",
        assistant_emoji: str = "🕵️‍♂️",
        max_width: str = "80%",
        card_max_width: str = "60%",
        font_size: str = None,
        mobile_font_size: str = None,
        padding: str = None,
        user_align: str = "right",
        assistant_align: str = "left",
        user_self_align: str = "flex-end",
        assistant_self_align: str = "flex-start",
        role_font_weight: str = None,
        role_font_size: str = None,
        role_margin_bottom: str = None,
        content_white_space: str = "normal",
        spinner_class: str = "spinner",
    ):
        # Use design system defaults or provided values
        self.colors = {
            "User": user_color or get_color("user_msg"),
            "Assistant": assistant_color or get_color("assistant_msg"),
        }

        self.emojis = {"User": user_emoji, "Assistant": assistant_emoji}

        self.alignments = {
            "User": {"text": user_align, "self": user_self_align},
            "Assistant": {"text": assistant_align, "self": assistant_self_align},
        }

        self.border_radii = {
            "User": f"{get_border_radius('md')} {get_border_radius('md')} 0em {get_border_radius('md')}",
            "Assistant": f"{get_border_radius('md')} {get_border_radius('md')} {get_border_radius('md')} 0em"
        }

        # Style configuration with design system defaults
        self.card_max_width = card_max_width
        self.max_width = max_width
        self.font_size = font_size or get_typography("2xl")
        self.mobile_font_size = mobile_font_size or get_typography("md")
        self.padding = padding or get_spacing("lg")
        self.role_font_weight = role_font_weight or get_typography("weight_bold")
        self.role_font_size = role_font_size or get_typography("lg")
        self.role_margin_bottom = role_margin_bottom or get_spacing("sm")
        self.content_white_space = content_white_space
        self.spinner_class = spinner_class

        # Build style template (fixed duplicate padding issue)
        self.style_template = f"""
        background: {{bg}}; color: {{text_color}}; font-size: {self.font_size};
        max-width: min({self.card_max_width}, {self.max_width}); align-self: {{self_align}};
        text-align: {{text_align}}; border-radius: {{border_radius}};
        padding: {self.padding}"""

    def _get_text_color(self, bg_color: str) -> str:
        """
        Calculate whether to use black or white text based on background color luminance.
        Uses the relative luminance formula from WCAG guidelines.
        """
        # Remove # if present
        hex_color = bg_color.lstrip("#")

        # Convert hex to RGB
        r = int(hex_color[0:2], 16) / 255.0
        g = int(hex_color[2:4], 16) / 255.0
        b = int(hex_color[4:6], 16) / 255.0

        # Calculate relative luminance
        def adjust_channel(c):
            return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

        r, g, b = adjust_channel(r), adjust_channel(g), adjust_channel(b)
        luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b

        # Return white for dark backgrounds, black for light backgrounds (using design system)
        return get_color("light_text") if luminance < 0.5 else get_color("dark_text")

    def _get_style(self, role: str) -> str:
        """Generate CSS style string for a given role."""
        bg_color = self.colors[role]
        return self.style_template.format(
            bg=bg_color,
            text_color=self._get_text_color(bg_color),
            self_align=self.alignments[role]["self"],
            text_align=self.alignments[role]["text"],
            border_radius=self.border_radii[role],
        )

    def _get_role_style(self) -> str:
        """Generate CSS style string for role labels."""
        return f"font-weight: {self.role_font_weight}; font-size: {self.role_font_size}; display: block; margin-bottom: {self.role_margin_bottom};"

    def get_mobile_styles(self) -> str:
        """Generate CSS media query for mobile devices."""
        return f"""
        {get_mobile_media_query()} {{
            .chat-card {{
                font-size: {self.mobile_font_size};
                padding: {get_spacing("sm")};
                max-width: 95%;
            }}
        }}
        """

    def render(self, data: dict):
        """
        Render a chat card with the given data.

        Args:
            data: Dictionary containing:
                - role: "User" or "Assistant"
                - content: Message content (optional)
                - pending: Boolean indicating if message is loading (optional)

        Returns:
            FastHTML Div element representing the chat card
        """
        role = data["role"]
        content = data.get("content", "")
        pending = data.get("pending", False)

        style = self._get_style(role)
        emoji = self.emojis[role]

        if pending:
            spinner = Span(cls=self.spinner_class)
            return Div(f"{emoji} {role}: ", spinner, style=style, cls="chat-card")

        # Add 'marked' class to enable markdown rendering
        return Div(
            Span(
                U(f"{emoji} {role}: "),
                style=self._get_role_style(),
            ),
            Div(
                content, cls="marked", style=f"white-space: {self.content_white_space};"
            ),
            style=style,
            cls="chat-card",
        )

    def __call__(self, data: dict):
        """Make the class callable like the original function."""
        return self.render(data)

# %% ../../nbs/0-Card.ipynb 7
CHAT_DIV_ID = "chat-cards"


def render_chat_list(messages: List[Dict[str, str]], ChatCard: ChatCard):
    return Div(
        Style(ChatCard.get_mobile_styles()),
        *[ChatCard(m) for m in messages],
        id=CHAT_DIV_ID,
        cls="chat-cards",
        style=f"display: flex; flex-direction: column; gap: {get_spacing('md')};",
    )

# %% ../../nbs/0-Card.ipynb 9
def mk_inp():
    return Input(
        id="msg",
        placeholder="Type a message...",
        autofocus=True,
        style=f"width: 60%; max-width: 600px; padding: {get_spacing('sm')}; font-size: {get_typography('md')}; border-radius: {get_border_radius('sm')}",
    )
